/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wumpus;

public class wumpusJNI {
  public final static native long new_engine(String jarg1);
  public final static native void delete_engine(long jarg1);
  public final static native String last_string(long jarg1);
  public final static native void execute(long jarg1, String jarg2);
  public final static native void handle_event(long jarg1, String jarg2);
  public final static native String initial_html(long jarg1);
  public final static native boolean is_shutdown_required(long jarg1);
  public final static native String last_response_json(long jarg1);
}
